Mobile and Desktop Version Implementation for Capstone Project
CVILLA09/capstone-project pull request #1
Opened 2023-07-07 21:57 UTC by CVILLA09

<h2>Description:</h2>

This pull request introduces the implementation of both mobile and desktop versions of the Capstone project. It includes:

- Addition of responsive design to the index.html and about.html pages to cater to various screen sizes.
- Styling updates in style.css and about.css to enhance the visual appeal and responsiveness of the website.
- JavaScript logic in main.js to handle dynamic elements on the webpage.

2023-07-07 23:47 UTC, CVILLA09 commented
<h1>Hello reviewer! 👋</h1>

<img src="https://media0.giphy.com/media/4ag7akAmeAfeKTwqxf/giphy.gif"/>

<p>I'm submitting this pull request for the review of my capstone project, which has now been deployed using GitHub Pages. However, I would like to bring your attention to an issue that I encountered with the stylelint linter:

"Invalid value for background-clip (style.css:126:3, style.css:691:5): This means you've used an invalid value for the background-clip property. The background-clip property can take the values border-box, padding-box, or content-box. Make sure you are using one of these valid values in your CSS."

I kindly request your feedback and guidance on how to address these stylelint linter errors effectively. If you have any information on how to solve them or another way to achieve the desired effect, it would be greatly appreciated.

Thank you in advance for your time and assistance. I'm looking forward to your valuable feedback! 🙏</p>

2023-07-08 02:04 UTC, bobb-Rob reviewed
Hi <STUDENT_MENTION>, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has unresolved conflict between the feature and main branch and that is why linters are not running even though you correctly set up GitHub action workflows. I suggest you fix the conflict issue and ensure that all linter errors are solved, if a particular styling is causing a linter error, simply replace it with another style property that does not cause an error. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-07-08 03:40 UTC, TadesseDev requested changes
### Hi @CVILLA09 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑🛑
![yPkfDFf](https://user-images.githubusercontent.com/69077061/204103543-ee5d8fa8-a37f-4177-b602-f22a28e022fb.gif)

You have submitted a project that has linter tests falling. Please make sure all linters are set up and passing before your next review request.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-08 04:14 UTC, shahadat3669 requested changes
Hi @CVILLA09 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

<img src="https://media1.giphy.com/media/jmqAUNFXAElgafPK0g/giphy.gif"/>

## Invalid Code Review Request

You have submitted a project that has linter tests falling. Please make sure all linters are set up and passing before your next review request.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-08 10:17 UTC, CVILLA09 commented
<h1>Hello again!!</h1>

<img src="https://media0.giphy.com/media/qQh0DBncuFJwQ/giphy.gif"/>

Just a quick message:

Could you please take a moment to read the first comment on the PR? 

I have initiated a thread in the support chat, but I would greatly appreciate some early feedback. Time is running out for me to submit the capstone project, so if there are any required changes to the design or overall functionality, I would prefer to address them promptly instead of waiting for a response and then scrambling to resolve any issues that may arise. Thank you for your assistance.

2023-07-08 12:28 UTC, LionRouge1 requested changes
Hi @CVILLA09, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

![almost](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights
- Good job deploying the website using GitHub page :+1: 
- Nice work following HTML & CSS and JavaScript best practices :1st_place_medal:   
- Great job adding appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) in you README file
## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] **Kindly check the node version that you're using on your local machine, it might be the cause of the linters errors that you're getting**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-07-08 12:28 UTC, LionRouge1 commented on index.html
> +            </nav>
- [ ] Kindly add the website's logo to the bottom white bar as in the provided design and make sure the navigation links for both bars are align (see image)
### Your design :point_down: 
![Screenshot from 2023-07-08 10-50-09](https://github.com/CVILLA09/capstone-project/assets/91142432/29f392a9-1a6f-46a7-94bd-062163ee9b76)
### What it is supposed to
![Screenshot from 2023-07-08 10-57-40](https://github.com/CVILLA09/capstone-project/assets/91142432/5037a57a-802a-48da-9347-35ae260c5287)
 look like :point_down:

2023-07-08 12:28 UTC, LionRouge1 commented on index.html
> +    </section>
- [ ] Nice work implementing the header :clap: However it would be nice to wrap it with a `header` tag for semantics reasons.

2023-07-08 12:28 UTC, LionRouge1 commented on index.html
> +        </section>
- [ ] Great job implementing the headline of the website :muscle: :sunglasses: However it not responsive, the elements overlap when reducing the screen. Kindly make sure the section is responsive on all screen for better user experience.
<video src="https://github.com/CVILLA09/capstone-project/assets/91142432/6132e767-dc63-4da3-8532-714259fb38ca" />

2023-07-08 12:28 UTC, LionRouge1 commented on about.html
> +    </section>
- [ ] Same here as pointed out earlier :point_up_2: It would be better to wrap this in a `header` tag.

2023-07-08 12:28 UTC, LionRouge1 commented on about.html
> +        </section>
- [ ] This section has a background image on the provided design. Kindly stick to the design as much as possible to follow the project requirement.
### Your design :point_down: 
![Screenshot from 2023-07-08 11-57-31](https://github.com/CVILLA09/capstone-project/assets/91142432/8e7e4074-a2a6-46c5-9eb8-acba6b7cbe3a)
### What it is supposed to look like :point_down: 
![Screenshot from 2023-07-08 11-57-55](https://github.com/CVILLA09/capstone-project/assets/91142432/ca6f44fc-63d1-47ed-901f-e7405a5ecb7f)

2023-07-08 12:28 UTC, LionRouge1 commented on main.js
> +};
- [ ] The button to see more speakers on the mobile version is not working when click on it. Kindly check it to make your project more professional.

2023-07-08 21:04 UTC, Lucas-Masaba approved these changes
# Hello @CVILLA09  👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![almost-there](https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)

## Highlights 🍾 
- Made changes as requested by the previous reviewers :+1: 
- Good communication on the challenges you were facing :speech_balloon: 

## Optional suggestions 💭 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-08 21:04 UTC, Lucas-Masaba commented on index.html
> +                <h2 class="event-date">2023.08.18 (FRI) ~ 20 (SUN)</h2>
[OPTIONAL]
- At a certain screen size, this text overlaps the next section as seen in the image. Please fix this when you get the time.
![image](https://github.com/CVILLA09/capstone-project/assets/45460192/1fcbbcb9-0783-427e-9805-3d5009f6e1f2)

2023-07-08 21:04 UTC, Lucas-Masaba commented on about.html
> +            <a href="index.html" class="logo-link">
[OPTIONAL]
- The logo here appears much smaller than the home page's logo. Please make them a similar size .such that your navigation bar can look uniform on both pages.
### About Page
![image](https://github.com/CVILLA09/capstone-project/assets/45460192/e1174aa6-d379-4842-86b6-1bcf6b18a07e)
### Home Page
![image](https://github.com/CVILLA09/capstone-project/assets/45460192/01bba4c4-f317-4611-b2ce-d77eeb9f7740)

2023-07-08 23:01 UTC, merged